let a = 123;
console.log(typeof a);
console.log(a);
let b = a.toString();
console.log(typeof b);
console.log(b);
console.log(typeof String(a));
console.log(typeof String(undefined));
console.log(typeof Number(b));
console.log(Number(b));
console.log(Number("123abc"));
console.log(Number(true));
console.log(Number(null));
console.log(parseInt("123px"));
console.log(Boolean(123));
console.log(Boolean(0));
console.log(Boolean(NaN));
console.log(Boolean(null));
console.log(Boolean(undefined));
console.log(Boolean(""));